task: elevation_v1
model_name: siglip-b16
weight_decay: 0.01
learning_rate: 0.001
epochs: 16
log_every_n_iter: 50
create_model_func:
  target: models.probe3d_backbones.SigLIPBackbone
  params:
    checkpoint: vit_base_patch16_siglip_384.webli
    pretrained: true
create_data_transform_func:
  target: models.probe3d_backbones.get_siglip_transform
feature_extractor_config:
  target: models.feature_extractor.Probe3DViTFeatureExtractor
  params:
    feat_type: patch
    layer: 8
probe_config:
  type: attn
  target: models.probes.AttentiveProbeModel
  params:
    in_features: 768
    num_classes: 2
data_config:
  num_workers: 4
  train:
    target: data.ElevationV1Dataset
    params:
      data_path: /disk/scratch_ssd/danier/data/elevation_v1/
      split: train
    batch_size: 64
  val:
    target: data.ElevationV1Dataset
    params:
      data_path: /disk/scratch_ssd/danier/data/elevation_v1/
      split: val
    batch_size: 64
  test:
    target: data.ElevationV1Dataset
    params:
      data_path: /disk/scratch_ssd/danier/data/elevation_v1/
      split: test
      return_path: true
    batch_size: 64
loss_config:
  target: utils.MultiMSEWithLogitsLoss
  params:
    target_scales:
    - 1
    - 0.625
metric_config:
  target: utils.HorizonErrorWithLogits
  params:
    target_scales:
    - 1
    - 0.625
