task: elevation_v1
model_name: stablediffusion
weight_decay: 0.01
learning_rate: 0.001
epochs: 16
log_every_n_iter: 50
create_model_func:
  target: models.probe3d_backbones.StableDiffusionBackbone
  params:
    model_id: stabilityai/stable-diffusion-2-1
    time_step: 1
    return_multilayer: true
feature_extractor_config:
  target: models.feature_extractor.Probe3DViTFeatureExtractor
  params:
    feat_type: patch
    layer: 1
probe_config:
  type: attn
  target: models.probes.AttentiveProbeModel
  params:
    in_features: __check__model__
    num_classes: 2
data_config:
  num_workers: 4
  train:
    target: data.ElevationV1Dataset
    params:
      data_path: /raid/danier/data/elevation_v1/
      split: train
    batch_size: 12
  val:
    target: data.ElevationV1Dataset
    params:
      data_path: /raid/danier/data/elevation_v1/
      split: val
    batch_size: 12
  test:
    target: data.ElevationV1Dataset
    params:
      data_path: /raid/danier/data/elevation_v1/
      split: test
      return_path: true
    batch_size: 12
loss_config:
  target: utils.MultiMSEWithLogitsLoss
  params:
    target_scales:
    - 1
    - 0.625
metric_config:
  target: utils.HorizonErrorWithLogits
  params:
    target_scales:
    - 1
    - 0.625
