task: size_v2
model_name: convnext-b16
weight_decay: 0.01
learning_rate: 0.001
epochs: 120
log_every_n_iter: 50
create_model_func:
  target: models.probe3d_backbones.ConvNextBackbone
  params:
    arch: convnext_base
feature_extractor_config:
  target: models.feature_extractor.Probe3DViTFeatureExtractor
  params:
    feat_type: mask
    layer: 3
    use_cls: false
probe_config:
  type: mlp
  target: models.probes.MlpProbeModel
  params:
    in_features: __check__model__
    num_classes: 1
data_config:
  num_workers: 4
  train:
    target: data.SizeV2Dataset
    params:
      data_path: /disk/scratch_ssd/danier/data/size_v2/
      split: train
      return_mask: true
    batch_size: 8
  val:
    target: data.SizeV2Dataset
    params:
      data_path: /disk/scratch_ssd/danier/data/size_v2/
      split: val
      return_mask: true
    batch_size: 8
  test:
    target: data.SizeV2Dataset
    params:
      data_path: /disk/scratch_ssd/danier/data/size_v2/
      split: test
      return_mask: true
      return_path: true
    batch_size: 8
loss_config:
  target: torch.nn.BCEWithLogitsLoss
