task: occlusion_v4
model_name: dinov2-b14
weight_decay: 0.01
learning_rate: 0.001
epochs: 10
log_every_n_iter: 50
create_model_func:
  target: timm.create_model
  params:
    model_name: vit_base_patch14_dinov2.lvd142m
    pretrained: true
    num_classes: 0
feature_extractor_config:
  target: models.feature_extractor.TimmViTFeatureExtractor
  params:
    feat_type: mask
    layer: 8
    use_cls: false
probe_config:
  type: mlp
  target: models.probes.MlpProbeModel
  params:
    in_features: 768
    num_classes: 1
data_config:
  num_workers: 4
  train:
    target: data.OcclusionV4Dataset
    params:
      data_path: /disk/scratch_ssd/danier/data/occlusion_v4/
      split: train
      return_mask: true
    batch_size: 8
  val:
    target: data.OcclusionV4Dataset
    params:
      data_path: /disk/scratch_ssd/danier/data/occlusion_v4/
      split: val
      return_mask: true
    batch_size: 8
  test:
    target: data.OcclusionV4Dataset
    params:
      data_path: /disk/scratch_ssd/danier/data/occlusion_v4/
      split: test
      return_mask: true
      return_path: true
    batch_size: 8
loss_config:
  target: torch.nn.BCEWithLogitsLoss
