task: occlusion_v4
model_name: resnext50
weight_decay: 0.01
learning_rate: 0.001
epochs: 10
log_every_n_iter: 50
create_model_func:
  target: models.resnet_backbones.ResNetBackbone
  params:
    model_name: resnext50_32x4d.tv_in1k
create_data_transform_func:
  target: models.resnet_backbones.get_resnet_transform
feature_extractor_config:
  target: models.feature_extractor.Probe3DViTFeatureExtractor
  params:
    feat_type: mask
    layer: 3
    use_cls: false
probe_config:
  type: mlp
  target: models.probes.MlpProbeModel
  params:
    in_features: __check__model__
    num_classes: 1
data_config:
  num_workers: 4
  train:
    target: data.OcclusionV4Dataset
    params:
      data_path: /raid/danier/data/occlusion_v4/
      split: train
      return_mask: true
    batch_size: 8
  val:
    target: data.OcclusionV4Dataset
    params:
      data_path: /raid/danier/data/occlusion_v4/
      split: val
      return_mask: true
    batch_size: 8
  test:
    target: data.OcclusionV4Dataset
    params:
      data_path: /raid/danier/data/occlusion_v4/
      split: test
      return_mask: true
      return_path: true
    batch_size: 8
loss_config:
  target: torch.nn.BCEWithLogitsLoss
