task: depth_diw
model_name: cliplora-b16
weight_decay: 0.001
learning_rate: 0.001
epochs: 1
log_every_n_iter: 50
create_model_func:
  target: models.lora.CLIPLoRA
  params:
    r: 4
    num_classes: 8
    train_with_cls: false
    train_upsample_factor: 7
    task_head: mlp
    lora_layer:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    ckpt: logs_finetune/finetune/cliplora-b16/all_cues/best_39.ckpt
    backbone:
      target: models.probe3d_backbones.CLIPBackbone
      params:
        arch: ViT-B-16
    use_orig_model: true
    assemble_mode: concat
create_data_transform_func:
  target: models.lora.get_cliplora_transform
feature_extractor_config:
  target: models.feature_extractor.Probe3DViTFeatureExtractor
  params:
    feat_type: dot
    layer: 11
    use_cls: false
probe_config:
  type: linear
  target: models.probes.LinearProbeModel
  params:
    in_features: 1536
    num_classes: 1
data_config:
  num_workers: 4
  train:
    target: data.diw.DIW
    params:
      data_path: /disk/scratch_ssd/danier/data/diw/
      split: train
    batch_size: 8
  val:
    target: data.diw.DIW
    params:
      data_path: /disk/scratch_ssd/danier/data/diw/
      split: val
    batch_size: 8
  test:
    target: data.diw.DIW
    params:
      data_path: /disk/scratch_ssd/danier/data/diw/
      split: test
      return_path: true
    batch_size: 8
loss_config:
  target: torch.nn.BCEWithLogitsLoss