task: depth_diw
model_name: dinov2lora-b14
weight_decay: 0.001
learning_rate: 0.001
epochs: 1
log_every_n_iter: 50
create_model_func:
  target: models.lora.TimmViTLoRA
  params:
    r: 4
    num_classes: 8
    train_with_cls: false
    train_upsample_factor: 7
    task_head: mlp
    lora_layer:
    - 11
    ckpt: logs_finetune/finetune/dinov2lora-b14/all_cues/best_39.ckpt
    backbone:
      target: models.vit.TimmViTBackbone
      params:
        model_name: vit_base_patch14_dinov2.lvd142m
    use_orig_model: true
    assemble_mode: concat
create_data_transform_func:
  target: models.lora.get_dinov2adapter_transform
feature_extractor_config:
  target: models.feature_extractor.Probe3DViTFeatureExtractor
  params:
    feat_type: dot
    layer: 11
    use_cls: false
probe_config:
  type: linear
  target: models.probes.LinearProbeModel
  params:
    in_features: 1536
    num_classes: 1
data_config:
  num_workers: 4
  train:
    target: data.diw.DIW
    params:
      data_path: /disk/scratch_ssd/danier/data/diw/
      split: train
    batch_size: 8
  val:
    target: data.diw.DIW
    params:
      data_path: /disk/scratch_ssd/danier/data/diw/
      split: val
    batch_size: 8
  test:
    target: data.diw.DIW
    params:
      data_path: /disk/scratch_ssd/danier/data/diw/
      split: test
      return_path: true
    batch_size: 8
loss_config:
  target: torch.nn.BCEWithLogitsLoss