task: depth_diw
model_name: resnet50
weight_decay: 0.001
learning_rate: 0.001
epochs: 1
log_every_n_iter: 50
create_model_func:
  target: models.resnet_backbones.ResNetBackbone
  params:
    model_name: resnet50.tv_in1k
create_data_transform_func:
  target: models.resnet_backbones.get_resnet_transform
feature_extractor_config:
  target: models.feature_extractor.Probe3DViTFeatureExtractor
  params:
    feat_type: dot
    layer: 4
    use_cls: false
probe_config:
  type: linear
  target: models.probes.LinearProbeModel
  params:
    in_features: __check__model__
    num_classes: 1
data_config:
  num_workers: 4
  train:
    target: data.diw.DIW
    params:
      data_path: /disk/scratch_ssd/danier/data/diw/
      split: train
    batch_size: 8
  val:
    target: data.diw.DIW
    params:
      data_path: /disk/scratch_ssd/danier/data/diw/
      split: val
    batch_size: 8
  test:
    target: data.diw.DIW
    params:
      data_path: /disk/scratch_ssd/danier/data/diw/
      split: test
      return_path: true
    batch_size: 8
loss_config:
  target: torch.nn.BCEWithLogitsLoss
