task: perspective_v1
model_name: midas-l16
weight_decay: 0.01
learning_rate: 0.001
epochs: 120
log_every_n_iter: 50
create_model_func:
  target: models.probe3d_backbones.MidasBackbone
  params:
    midas: true
feature_extractor_config:
  target: models.feature_extractor.Probe3DViTFeatureExtractor
  params:
    feat_type: patch
    layer: 11
probe_config:
  type: attn
  target: models.probes.AttentiveProbeModel
  params:
    in_features: 1024
    num_classes: 2
data_config:
  num_workers: 4
  train:
    target: data.PerspectiveV1Dataset
    params:
      data_path: /raid/danier/data/perspective_v1/
      split: train
    batch_size: 64
  val:
    target: data.PerspectiveV1Dataset
    params:
      data_path: /raid/danier/data/perspective_v1/
      split: val
    batch_size: 64
  test:
    target: data.PerspectiveV1Dataset
    params:
      data_path: /raid/danier/data/perspective_v1/
      split: test
      return_path: true
    batch_size: 64
loss_config:
  target: utils.MSEWithLogitsLoss
  params:
    target_range:
    - -1.5
    - 1.5
metric_config:
  target: utils.EuclideanDistanceWithLogits
  params:
    target_range:
    - -1.5
    - 1.5
